# Generated by Django 6.0.5 on 2026-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='application_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='application_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='is_adjunct_researcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='qualification',
            field=models.TextField(blank=True),
        ),
    ]
