# Generated by Django 6.0.5 on 2026-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researcherprofile_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='application_letter',
            field=models.FileField(blank=True, null=True, upload_to='application_letters/'),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='brief_profile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='grants_fellowships',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='publications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
