# Generated by Django 6.0.5 on 2026-05-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_researcherprofile_application_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=300)),
                ('publication_year', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('doi_link', models.URLField(blank=True)),
                ('publication_pdf', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_list', to='accounts.researcherprofile')),
            ],
        ),
    ]
